-- Aurora Bank - Oracle schema + seed data
-- This is the LEGACY database the Spring Boot 1.5 / Java 8 app talks to.
-- Run as the AURORA schema owner.

-- ---- Drop (ignore errors on first run) -------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE LEDGER_ENTRY'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TRANSFER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ACCOUNT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE HIBERNATE_SEQUENCE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Hibernate AUTO id generation uses a shared sequence on Oracle.
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1000 INCREMENT BY 1 NOCACHE;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID  NUMBER(19)     PRIMARY KEY,
    FULL_NAME    VARCHAR2(200)  NOT NULL,
    EMAIL        VARCHAR2(200),
    STATUS       VARCHAR2(20)   NOT NULL
);

CREATE TABLE ACCOUNT (
    ACCOUNT_ID      NUMBER(19)     PRIMARY KEY,
    ACCOUNT_NUMBER  VARCHAR2(40)   NOT NULL,
    CUSTOMER_ID     NUMBER(19)     NOT NULL REFERENCES CUSTOMER(CUSTOMER_ID),
    ACCOUNT_TYPE    VARCHAR2(20)   NOT NULL,
    CURRENCY        VARCHAR2(3)    NOT NULL,
    BALANCE         BINARY_DOUBLE  NOT NULL,
    STATUS          VARCHAR2(20)   NOT NULL,
    OPENED_AT       TIMESTAMP      NOT NULL
);

CREATE TABLE LEDGER_ENTRY (
    ENTRY_ID     NUMBER(19)     PRIMARY KEY,
    ACCOUNT_ID   NUMBER(19)     NOT NULL REFERENCES ACCOUNT(ACCOUNT_ID),
    ENTRY_TYPE   VARCHAR2(10)   NOT NULL,
    AMOUNT       BINARY_DOUBLE  NOT NULL,
    DESCRIPTION  VARCHAR2(400),
    POSTED_AT    TIMESTAMP      NOT NULL
);

CREATE TABLE TRANSFER (
    TRANSFER_ID      NUMBER(19)     PRIMARY KEY,
    REFERENCE        VARCHAR2(60)   NOT NULL,
    FROM_ACCOUNT_ID  NUMBER(19)     NOT NULL,
    TO_ACCOUNT_ID    NUMBER(19)     NOT NULL,
    AMOUNT           BINARY_DOUBLE  NOT NULL,
    STATUS           VARCHAR2(20)   NOT NULL,
    CREATED_AT       TIMESTAMP      NOT NULL
);

-- ---- Seed data -------------------------------------------------------------

INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, EMAIL, STATUS) VALUES (1, 'Anna Schmidt',     'anna.schmidt@example.com', 'ACTIVE');
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, EMAIL, STATUS) VALUES (2, 'Marco Rossi',      'marco.rossi@example.com',  'ACTIVE');
INSERT INTO CUSTOMER (CUSTOMER_ID, FULL_NAME, EMAIL, STATUS) VALUES (3, 'Sophie Laurent',   'sophie.laurent@example.com','ACTIVE');

INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NUMBER, CUSTOMER_ID, ACCOUNT_TYPE, CURRENCY, BALANCE, STATUS, OPENED_AT)
    VALUES (10, 'ACC-1001', 1, 'CHECKING', 'EUR', 2500.00, 'ACTIVE', TIMESTAMP '2021-03-01 09:00:00');
INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NUMBER, CUSTOMER_ID, ACCOUNT_TYPE, CURRENCY, BALANCE, STATUS, OPENED_AT)
    VALUES (11, 'ACC-1002', 1, 'SAVINGS',  'EUR', 18000.00,'ACTIVE', TIMESTAMP '2021-03-01 09:05:00');
INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NUMBER, CUSTOMER_ID, ACCOUNT_TYPE, CURRENCY, BALANCE, STATUS, OPENED_AT)
    VALUES (12, 'ACC-2001', 2, 'CHECKING', 'EUR', 540.50,  'ACTIVE', TIMESTAMP '2022-07-12 14:30:00');
INSERT INTO ACCOUNT (ACCOUNT_ID, ACCOUNT_NUMBER, CUSTOMER_ID, ACCOUNT_TYPE, CURRENCY, BALANCE, STATUS, OPENED_AT)
    VALUES (13, 'ACC-3001', 3, 'SAVINGS',  'EUR', 75.00,   'FROZEN', TIMESTAMP '2023-01-20 11:15:00');

INSERT INTO LEDGER_ENTRY (ENTRY_ID, ACCOUNT_ID, ENTRY_TYPE, AMOUNT, DESCRIPTION, POSTED_AT)
    VALUES (100, 10, 'CREDIT', 2500.00, 'Opening deposit', TIMESTAMP '2021-03-01 09:00:00');
INSERT INTO LEDGER_ENTRY (ENTRY_ID, ACCOUNT_ID, ENTRY_TYPE, AMOUNT, DESCRIPTION, POSTED_AT)
    VALUES (101, 11, 'CREDIT', 18000.00,'Opening deposit', TIMESTAMP '2021-03-01 09:05:00');

INSERT INTO TRANSFER (TRANSFER_ID, REFERENCE, FROM_ACCOUNT_ID, TO_ACCOUNT_ID, AMOUNT, STATUS, CREATED_AT)
    VALUES (500, 'TRF-SEED-1', 11, 10, 500.00, 'POSTED', TIMESTAMP '2024-02-10 10:00:00');

COMMIT;
